### ISSUE TITLE
deprecate_field does unnecessary conversion to NullBooleanField

### ISSUE THREAD

**Issue by tildedave** [3YOURMIND/django-deprecate-fields#11]
Hi there, Django supports BooleanField(null=True) since Django 2.1 - https://docs.djangoproject.com/en/2.1/ref/models/fields/#django.db.models.BooleanField

If you try to deprecate one of these through the library, it ends up creating a no-op migration to switch the field to a NullBooleanField.  It would be better to detect this scenario and not create a migration in this instance.

**Comment by flixx** [comment]
I merged and closed this issue.

However, I also needed to drop support for Django 2.0 and earlier.
Since Django 2.0 is very old and the NullBooleanField is deprecated in Django 3.1, I think that it is worth it.

Thanks for raising the issue and thanks again @theilgaard for contributing.
flixx

**Comment by tuky** [comment]
Just want to mention, that with this we now have to touch our historic migrations. Django by itself does not require this, because old migrations are allowed to keep their usage of `NullBooleanField`.
