### ISSUE TITLE
Logger should be instantiated with `__name__`

### ISSUE THREAD

**Issue by fredrikgyll** [3YOURMIND/django-deprecate-fields#25]
The logger in [deprecate_field.py](https://github.com/3YOURMIND/django-deprecate-fields/blob/75f62c2713f4a98c86e7a975c8996e082305521b/django_deprecate_fields/deprecate_field.py#L5) is instantiated with `__file__` which makes the logger uncontrollable from the `LOGGING` setting. Could it be changed to `__name__` ?

**Comment by fevral13** [comment]
thank you @fredrikgyll
